export const fetchActionTypes = {
  DATA_FETCHED: "DATA_FETCHED",
  FETCH_NEW_RESOURCE: "FETCH_NEW_RESOURCE",
  FETCHING_ERROR: "FETCHING_ERROR",
  START_FETCHING: "START_FETCHING"
}

export const filtersActionTypes = {
  SET_SORT_FILTER: "SET_SORT_FILTER",
  SET_PERIOD_FILTER: "SET_PERIOD_FILTER",
  SET_GRID_SIZE_FILTER: "SET_GRID_SIZE_FILTER",
  SET_SEARCH_FILTER: "SET_SEARCH_FILTER"
};

export const paginationActionTypes = {
  SWITCH_PAGE: "SWITCH_PAGE",
  LOAD_NEW_PAGE_INDEXES: "LOAD_NEW_PAGE_INDEXES",
  SHOW_DEFAULT_PAGE: "SHOW_DEFAULT_PAGE"
};
